task01 numpy

In [ ]:
import numpy as np


def softmax(x):
    e_x=np.exp(x-np.max(x))
    return e_x/e_x.sum()

x1=np.array([1.0,2.0,3.0])
x2=np.array([4.0,5.0,6.0])

x=np.stack([x1,x2])

w1=np.array([[0.1,0.2,0.3,0.4],[0.5,0.6,0.7,0.8],[0.9,1.0,1.1,1.2]],dtype=np.float32)
w2=np.array([[0.2,0.1],[0.4,0.5],[0.6,0.2],[0.8,0.7]],dtype=np.float32)

hidden_layer=np.maximum(np.dot(x,),0)


output_Layer=np.exp(np.dot(hidden_layer,w2))/np.sum(np.exp(np.dot(hidden_layer,w2)),axis=1,keepdims=True)

print("Output layer: ",output_Layer)

[[10.0000004   7.50000011]
 [22.6000009  16.95000023]]
Output layer:  [[0.92414184 0.07585816]
 [0.99649482 0.00350518]]


task 01 pytorch

In [7]:
# Input layer with 3 nodes
# Hidden layer with 4 nodes and ReLU activation
# Output layer with 2 nodes and softmax activation

import torch
import torch.nn as nn
import torch.nn.functional as F


gpu_avail=torch.cuda.is_available()
print("GPU available: ",gpu_avail)
if gpu_avail:
    device=torch.device("cuda")
else:
    device=torch.device("cpu")
print("Device: ",device)

# Generate intputData
x1=torch.tensor([1.0,2.0,3.0])
x2=torch.tensor([4.0,5.0,6.0])

x=torch.stack([x1,x2])

# Generate weights
w1=torch.tensor([[0.1,0.2,0.3,0.4],[0.5,0.6,0.7,0.8],[0.9,1.0,1.1,1.2]],dtype=torch.float32)
w2=torch.tensor([[0.2,0.1],[0.4,0.5],[0.6,0.2],[0.8,0.7]],dtype=torch.float32)


# Generate hidden layer
hidden_layer=F.relu(torch.matmul(x,w1))

output_layer=F.softmax(torch.matmul(hidden_layer,w2),dim=1)


print("Output layer: ",output_layer)

GPU available:  True
Device:  cuda
Output layer:  tensor([[0.9241, 0.0759],
        [0.9965, 0.0035]])


task02 numpy

In [8]:
import numpy as np

# --- Activation & loss helpers ---
def relu(x):
    return np.maximum(0, x)

def softmax(x, axis=1):
    x = x - np.max(x, axis=axis, keepdims=True)
    e = np.exp(x)
    return e / np.sum(e, axis=axis, keepdims=True)

def cross_entropy(output, target):
    return -np.sum(target * np.log(output), axis=1).mean()

# --- Data & weights (no bias) ---
x = np.stack([
    np.array([0.1, 0.2, 0.3]),
    np.array([0.4, 0.5, 0.6])
])  # shape (2,3)

w1 = np.array([
    [0.1, 0.2, 0.3, 0.4],
    [0.5, 0.6, 0.7, 0.8],
    [0.9, 1.0, 1.1, 1.2]
])
w2 = np.array([
    [0.2, 0.1],
    [0.4, 0.5],
    [0.6, 0.2],
    [0.8, 0.7]
])

# --- Forward pass ---
hidden = relu(x.dot(w1))               # (2,4)
output = softmax(hidden.dot(w2), axis=1)  # (2,2)

target = np.array([[0,1],[1,0]])       # one-hot labels

loss = cross_entropy(output, target)
print("Loss:", loss)

# --- Backprop to compute ∂Loss/∂w1 ---
batch_size = x.shape[0]

# dL/d_logits_out = (output - target) / batch_size
delta_out = (output - target) / batch_size  # (2,2)

# Propagate through w2 into hidden
delta_hidden = delta_out.dot(w2.T)          # (2,4)
delta_hidden[hidden <= 0] = 0               # ReLU gradient

# Finally gradient of w1: x^T · delta_hidden
grad_w1 = x.T.dot(delta_hidden)             # (3,4)

print("Gradient of w1:\n", grad_w1)

Loss: 0.6379850004327519
Gradient of w1:
 [[-0.00443694  0.00443694 -0.01774778 -0.00443694]
 [-0.00343802  0.00343802 -0.01375207 -0.00343802]
 [-0.00243909  0.00243909 -0.00975637 -0.00243909]]


task02 pytorch

In [9]:
import torch
import torch.nn as nn
import torch.nn.functional as F

gpu_avail=torch.cuda.is_available()
print("GPU available: ",gpu_avail)
if gpu_avail:
    device=torch.device("cuda")
else:
    device=torch.device("cpu")
print("Device: ",device)

def cross_entropy_loss(output,target):
    return -(target*torch.log(output)).sum(dim=1).mean()

# Generate data
x1=torch.tensor([0.1,0.2,0.3],dtype=torch.float32)
x2=torch.tensor([0.4,0.5,0.6],dtype=torch.float32)
x=torch.stack([x1,x2])

w1=torch.tensor([[0.1,0.2,0.3,0.4],[0.5,0.6,0.7,0.8],[0.9,1.0,1.1,1.2]],dtype=torch.float32,requires_grad=True)
w2=torch.tensor([[0.2,0.1],[0.4,0.5],[0.6,0.2],[0.8,0.7]],dtype=torch.float32)

hidden_layer=F.relu(torch.matmul(x,w1))

output_layer=F.softmax(torch.matmul(hidden_layer,w2),dim=1)

# print("Output layer: ",output_layer)

target=torch.tensor([[0,1],[1,0]],dtype=torch.float32)
loss=cross_entropy_loss(output_layer,target)


loss.backward()

print("Gradient of w1: ",w1.grad)



GPU available:  True
Device:  cuda
Gradient of w1:  tensor([[-0.0044,  0.0044, -0.0177, -0.0044],
        [-0.0034,  0.0034, -0.0138, -0.0034],
        [-0.0024,  0.0024, -0.0098, -0.0024]])


task03 numpy

task03 pytorch